#pragma once


#define kPalettes_Intro ((uint16*)RomFixedPtr(0x8ce3e9))
#define kPalettes_SpaceGunshipCeres ((uint16*)RomFixedPtr(0x8ce5e9))
#define kPalettes_PostCredits ((uint16*)RomFixedPtr(0x8ce7e9))
#define kPalettes_Credits ((uint16*)RomFixedPtr(0x8ce9e9))
#define kPalettes_ZebesExplosion ((uint16*)RomFixedPtr(0x8cebe9))
#define kPalettes_ZebesExplosionClouds ((uint16*)RomFixedPtr(0x8cede9))
#define kInitialIntro_JapaneseTextTilemap ((uint16*)RomFixedPtr(0x8cd81b))
#define kPage1Intro_JapaneseTextRegion ((uint16*)RomFixedPtr(0x8ba72b))
#define kLevelData_MotherBrainRoomFromCutscene ((uint16*)RomFixedPtr(0x8cbec3))
#define kLevelData_RoomWithBabyMetroidHatching ((uint16*)RomFixedPtr(0x8cc083))
#define kCredits_DeerForceTilemap ((uint16*)RomFixedPtr(0x8cdc9b))
#define kCredits_1994NintendoCredits ((uint16*)RomFixedPtr(0x8cdedb))
#define kPalettes_EndingSuperMetroidIconGlare ((uint16*)RomFixedPtr(0x8cefe9))
#define kCredits_ItemPercentageRamAddresses ((uint16*)RomFixedPtr(0x8be70d))
#define kCredits_ItemPercentageDivisors ((uint16*)RomFixedPtr(0x8be717))
#define kCredits_ItemPercentageItemBits ((uint16*)RomFixedPtr(0x8be721))
#define kCredits_ItemPercentageBeamBits ((uint16*)RomFixedPtr(0x8be737))
#define kCredits_ItemPercentageDigitsTilemap ((uint16*)RomFixedPtr(0x8be741))
#define kShootingStarTable ((uint16*)RomFixedPtr(0x8be9cf))
#define kCinematicFunction_Intro_Func142_Tab0 ((uint16*)RomFixedPtr(0x8be45a))
#define kCinematicFunction_Intro_Func144_Tab0 ((uint16*)RomFixedPtr(0x8be5e7))
#define kCredits_ItemPercentageJapaneseTextTilemap ((uint16*)RomFixedPtr(0x8cdf5b))
#define kShootingStarTileNumberAttributes ((uint16*)RomFixedPtr(0x8be9a7))
#define kCinematicFunction_Intro_Func216_SourceAddresses ((uint16*)RomFixedPtr(0x8bf6b8))
#define kCinematicFunction_Intro_Func216_VramAddresses ((uint16*)RomFixedPtr(0x8bf6d8))
#define kPalettes_TitleScreen ((uint16*)RomFixedPtr(0x8ce1e9))
#define kTitleSequenceHdmaTablePtrs ((uint16*)RomFixedPtr(0x8cbc5d))