#pragma once

// Clockwise
#define ROTATE_CW 0
// Counterclockwise
#define ROTATE_CCW 0x8000

static uint16 kFxTypeTilemapPtrs[23] = {  // 0x83ABF0
  [kFxType_0_None>>1]                   = 0x0,
  [kFxType_2_Lava>>1]                   = addr_kTilemap_Lava,
  [kFxType_4_Acid>>1]                   = addr_kTilemap_Acid,
  [kFxType_6_Water>>1]                  = addr_kTilemap_Water,
  [kFxType_8_Spores>>1]                 = addr_kTilemap_Spores,
  [kFxType_A_Rain>>1]                   = addr_kTilemap_Rain,
  [kFxType_C_Fog>>1]                    = addr_kTilemap_Fog,
  [0xe>>1]                              = 0x0,
  [0x10>>1]                             = 0x0,
  [0x12>>1]                             = 0x0,
  [0x14>>1]                             = 0x0,
  [0x16>>1]                             = 0x0,
  [0x18>>1]                             = 0x0,
  [0x1a>>1]                             = 0x0,
  [0x1c>>1]                             = 0x0,
  [0x1e>>1]                             = 0x0,
  [kFxType_20_ScrollingSkyLand>>1]      = 0x0,
  [kFxType_22_Unused>>1]                = 0x0,
  [kFxType_24_Fireflea>>1]              = 0x0,
  [kFxType_26_TourianEntranceStatue>>1] = addr_kTilemap_Water,
  // In the original code, this table is actually too short, so it reads data from the next table
  // Thus these values end up reading garbage into VRAM, but is luckily not displayed
  [kFxType_28_CeresRidley>>1]           = 0xb278,
  [kFxType_2A_CeresElevator>>1]         = 0xb279,
  [kFxType_2C_Haze>>1]                  = 0xb2a1,
};

void nullsub_106(void) {}

static Func_V *const kFxTypeFuncPtrs[23] = {  // 0x83AC18
  nullsub_106,
  FxTypeFunc_2_Lava,
  FxTypeFunc_4_Acid,
  FxTypeFunc_6_Water,
  FxTypeFunc_8_Spores,
  FxTypeFunc_A_Rain,
  FxTypeFunc_C_Fog,
  nullsub_106,
  nullsub_106,
  nullsub_106,
  nullsub_106,
  nullsub_106,
  nullsub_106,
  nullsub_106,
  nullsub_106,
  nullsub_106,
  FxTypeFunc_20_ScrollingSkyLand,
  FxTypeFunc_22_Unused,
  FxTypeFunc_24_Fireflea,
  FxTypeFunc_26_TourianEntranceStatue,
  FxTypeFunc_28_CeresRidley,
  FxTypeFunc_2A_CeresElevator,
  FxTypeFunc_2C_Haze,
};

static uint16 kAreaPalFxLists[8][8] = {  // 0x83AC46
  [kArea_0_Crateria]    = { addr_kPalfx_Crateria_1_Lightning                                   , addr_kPalfx_Crateria_2_RedFlashing_UpperCrateria                   , addr_kPalfx_Crateria_4_YellowLightning                             , addr_kPalfx_Crateria_8_RedFlashing_OldTourian                      , addr_kPalfx_Crateria_16_OrangeFlashing_OldTourian_BackgroundRails  , addr_kPalfx_Crateria_32_YellowFlashing_OldTourian_BackgroundPanels , addr_kPalfx_Crateria_64_PixelChange                                , addr_kPalfx_Crateria_128_Brinstar_4_BeaconFlashing                 , },
  [kArea_1_Brinstar]    = { addr_kPalfx_Brinstar_1_BlueBgSpores                                , addr_kPalfx_Brinstar_2_RedBgGlow                                   , addr_kPalfx_Crateria_128_Brinstar_4_BeaconFlashing                 , addr_kPalfx_Brinstar_8_SporeSpawn_BlueBgSpores                     , addr_kPalfx_Nothing                                                , addr_kPalfx_Nothing                                                , addr_kPalfx_Nothing                                                , addr_kPalfx_Nothing                                                , },
  [kArea_2_Norfair]     = { addr_kPalfx_Norfair_1_Tourian_1                                    , addr_kPalfx_Norfair_2                                              , addr_kPalfx_Norfair_4                                              , addr_kPalfx_Norfair_8                                              , addr_kPalfx_Norfair_16                                             , addr_kPalfx_Nothing                                                , addr_kPalfx_Nothing                                                , addr_kPalfx_Nothing                                                , },
  [kArea_3_WreckedShip] = { addr_kPalfx_WreckedShip_1_GreenLights                              , addr_kPalfx_Nothing                                                , addr_kPalfx_Nothing                                                , addr_kPalfx_Nothing                                                , addr_kPalfx_Nothing                                                , addr_kPalfx_Nothing                                                , addr_kPalfx_Nothing                                                , addr_kPalfx_Nothing                                                , },
  [kArea_4_Maridia]     = { addr_kPalfx_Maridia_1_SandPits                                     , addr_kPalfx_Maridia_2_SandFalls                                    , addr_kPalfx_Maridia_4_BgWaterfalls                                 , addr_kPalfx_Nothing                                                , addr_kPalfx_Nothing                                                , addr_kPalfx_Nothing                                                , addr_kPalfx_Nothing                                                , addr_kPalfx_Nothing                                                , },
  [kArea_5_Tourian]     = { addr_kPalfx_Norfair_1_Tourian_1                                    , addr_kPalfx_Tourian_2_Glowing_ArkanoidBlocksAndOrbs                , addr_kPalfx_Tourian_4_UnusedTourian2Clone                          , addr_kPalfx_Tourian_8_RedFlashing_Shutter                          , addr_kPalfx_Tourian_16_RedFlashing_Background                      , addr_kPalfx_Tourian_32_RedFlashing_GeneralLevel                    , addr_kPalfx_Tourian_64_RedFlashing_ArkanoidBlocksAndOrbs           , addr_kPalfx_Nothing                                                , },
  [kArea_6_Ceres]       = { addr_kPalfx_Nothing                                                , addr_kPalfx_Nothing                                                , addr_kPalfx_Nothing                                                , addr_kPalfx_Nothing                                                , addr_kPalfx_Nothing                                                , addr_kPalfx_Nothing                                                , addr_kPalfx_Nothing                                                , addr_kPalfx_Nothing                                                , },
  [kArea_7_Debug]       = { addr_kPalfx_Nothing                                                , addr_kPalfx_Nothing                                                , addr_kPalfx_Nothing                                                , addr_kPalfx_Nothing                                                , addr_kPalfx_Nothing                                                , addr_kPalfx_Nothing                                                , addr_kPalfx_Nothing                                                , addr_kPalfx_Nothing                                                , },
};

static uint16 kAreaAnimtilesLists[8][8] = {  // 0x83AC56
  [kArea_0_Crateria]    = { addr_kAnimTiles_HorizontalSpikes          , addr_kAnimTiles_VerticalSpikes            , addr_kAnimTiles_CrateriaLake              , addr_kAnimTiles_CrateriaLava_Unused1      , addr_kAnimTiles_Nothing                   , addr_kAnimTiles_Nothing                   , addr_kAnimTiles_Nothing                   , addr_kAnimTiles_Nothing                   , },
  [kArea_1_Brinstar]    = { addr_kAnimTiles_HorizontalSpikes          , addr_kAnimTiles_VerticalSpikes            , addr_kAnimTiles_BrinstarMouth             , addr_kAnimTiles_Nothing                   , addr_kAnimTiles_Nothing                   , addr_kAnimTiles_Nothing                   , addr_kAnimTiles_Nothing                   , addr_kAnimTiles_Nothing                   , },
  [kArea_2_Norfair]     = { addr_kAnimTiles_HorizontalSpikes          , addr_kAnimTiles_VerticalSpikes            , addr_kAnimTiles_Nothing                   , addr_kAnimTiles_Nothing                   , addr_kAnimTiles_Nothing                   , addr_kAnimTiles_Nothing                   , addr_kAnimTiles_Nothing                   , addr_kAnimTiles_Nothing                   , },
  [kArea_3_WreckedShip] = { addr_kAnimTiles_HorizontalSpikes          , addr_kAnimTiles_VerticalSpikes            , addr_kAnimtiles_WreckedShipTreadmillRight , addr_kAnimtiles_WreckedShipTreadmillLeft  , addr_kAnimTiles_WreckedShipScreen         , addr_kAnimTiles_Nothing                   , addr_kAnimTiles_Nothing                   , addr_kAnimTiles_Nothing                   , },
  [kArea_4_Maridia]     = { addr_kAnimTiles_HorizontalSpikes          , addr_kAnimTiles_VerticalSpikes            , addr_kAnimTiles_MaridiaSandCeiling        , addr_kAnimTiles_MaridiaSandFalling        , addr_kAnimTiles_Nothing                   , addr_kAnimTiles_Nothing                   , addr_kAnimTiles_Nothing                   , addr_kAnimTiles_Nothing                   , },
  [kArea_5_Tourian]     = { addr_kAnimTiles_HorizontalSpikes          , addr_kAnimTiles_VerticalSpikes            , addr_kAnimTiles_Nothing                   , addr_kAnimTiles_Nothing                   , addr_kAnimTiles_Nothing                   , addr_kAnimTiles_Nothing                   , addr_kAnimTiles_Nothing                   , addr_kAnimTiles_Nothing                   , },
  [kArea_6_Ceres]       = { addr_kAnimTiles_HorizontalSpikes          , addr_kAnimTiles_VerticalSpikes            , addr_kAnimTiles_Nothing                   , addr_kAnimTiles_Nothing                   , addr_kAnimTiles_Nothing                   , addr_kAnimTiles_Nothing                   , addr_kAnimTiles_Nothing                   , addr_kAnimTiles_Nothing                   , },
  [kArea_7_Debug]       = { addr_kAnimTiles_HorizontalSpikes          , addr_kAnimTiles_VerticalSpikes            , addr_kAnimTiles_Nothing                   , addr_kAnimTiles_Nothing                   , addr_kAnimTiles_Nothing                   , addr_kAnimTiles_Nothing                   , addr_kAnimTiles_Nothing                   , addr_kAnimTiles_Nothing                   , },
};

static uint16 kPaletteBlends[] = {  // 0x89AA02
	   0x0,  0xe3f,  0xd7f,    0x0, 0x6318, 0x6318,    0x0, 0x6318, 0x6318,    0x0, 0x6318, 0x6318,    0x0, 0x6318, 0x6318,    0x0, 
	0x3800, 0x314a, 0x20c6,  0x820, 0x6318, 0x6318,    0x0, 0x6318, 0x6318,    0x0, 0x6318, 0x6318,    0x0, 0x6318, 0x6318,    0x0, 
	0x3800,  0x400, 0x1c63,    0x0, 0x28e3, 0x1c60,    0x0, 0x2485, 0x3d88,    0x0,  0x880,  0x420,    0x0, 0x28e3, 0x1c60,    0x0, 
	0x3800, 0x20a5, 0x1c84, 0x1024, 0x1087, 0x14a8,  0x844, 0x6318, 0x6318,    0x0, 0x6318, 0x6318,    0x0, 0x6318, 0x6318,    0x0, 
	0x3800, 0x6318, 0x6318,    0x0, 0x6318, 0x6318,    0x0, 0x6318, 0x6318,    0x0, 0x6318, 0x6318,    0x0, 0x6318, 0x6318,    0x0, 
	0x3800, 0x6318, 0x6318,    0x0, 0x6318, 0x6318,    0x0, 0x6318, 0x6318,    0x0, 0x6318, 0x6318,    0x0, 0x6318, 0x6318,    0x0, 
	0x3800, 0x6318, 0x6318,    0x0, 0x6318, 0x6318,    0x0, 0x6318, 0x6318,    0x0, 0x6318, 0x6318,    0x0, 0x6318, 0x6318,    0x0, 
	0x3800,  0x400, 0x18a2,    0x0,   0x20,  0xc62,    0x0,  0x400, 0x1c45,    0x0, 0x6318, 0x6318,    0x0, 0x6318, 0x6318,    0x0,
};

static RotationMatrix kCeresElevatorShaftMode7TransformationMatrix[69] = {  // 0x89AD5F
  [0]  = { .timer = 60, .sin_t = -34, .cos_t = 254 },
  [1]  = { .timer = 26, .sin_t = -33, .cos_t = 254 },
  [2]  = { .timer = 24, .sin_t = -32, .cos_t = 254 },
  [3]  = { .timer = 22, .sin_t = -31, .cos_t = 254 },
  [4]  = { .timer = 20, .sin_t = -30, .cos_t = 254 },
  [5]  = { .timer = 18, .sin_t = -29, .cos_t = 254 },
  [6]  = { .timer = 16, .sin_t = -28, .cos_t = 254 },
  [7]  = { .timer = 14, .sin_t = -27, .cos_t = 255 },
  [8]  = { .timer = 12, .sin_t = -26, .cos_t = 255 },
  [9]  = { .timer = 11, .sin_t = -25, .cos_t = 255 },
  [10] = { .timer = 10, .sin_t = -24, .cos_t = 255 },
  [11] = { .timer =  9, .sin_t = -23, .cos_t = 255 },
  [12] = { .timer =  8, .sin_t = -22, .cos_t = 255 },
  [13] = { .timer =  7, .sin_t = -21, .cos_t = 255 },
  [14] = { .timer =  7, .sin_t = -20, .cos_t = 255 },
  [15] = { .timer =  6, .sin_t = -19, .cos_t = 255 },
  [16] = { .timer =  6, .sin_t = -18, .cos_t = 255 },
  [17] = { .timer =  5, .sin_t = -17, .cos_t = 255 },
  [18] = { .timer =  5, .sin_t = -16, .cos_t = 256 },
  [19] = { .timer =  4, .sin_t = -15, .cos_t = 256 },
  [20] = { .timer =  4, .sin_t = -14, .cos_t = 256 },
  [21] = { .timer =  4, .sin_t = -13, .cos_t = 256 },
  [22] = { .timer =  3, .sin_t = -12, .cos_t = 256 },
  [23] = { .timer =  3, .sin_t = -11, .cos_t = 256 },
  [24] = { .timer =  3, .sin_t = -10, .cos_t = 256 },
  [25] = { .timer =  3, .sin_t =  -9, .cos_t = 256 },
  [26] = { .timer =  2, .sin_t =  -8, .cos_t = 256 },
  [27] = { .timer =  2, .sin_t =  -7, .cos_t = 256 },
  [28] = { .timer =  2, .sin_t =  -6, .cos_t = 256 },
  [29] = { .timer =  2, .sin_t =  -5, .cos_t = 256 },
  [30] = { .timer =  1, .sin_t =  -4, .cos_t = 256 },
  [31] = { .timer =  1, .sin_t =  -3, .cos_t = 256 },
  [32] = { .timer =  1, .sin_t =  -2, .cos_t = 256 },
  [33] = { .timer =  1, .sin_t =  -1, .cos_t = 256 },
  [34] = { .timer =  1, .sin_t =   0, .cos_t = 256 },
  [35] = { .timer =  1, .sin_t =   1, .cos_t = 256 },
  [36] = { .timer =  1, .sin_t =   2, .cos_t = 256 },
  [37] = { .timer =  1, .sin_t =   3, .cos_t = 256 },
  [38] = { .timer =  1, .sin_t =   4, .cos_t = 256 },
  [39] = { .timer =  2, .sin_t =   5, .cos_t = 256 },
  [40] = { .timer =  2, .sin_t =   6, .cos_t = 256 },
  [41] = { .timer =  2, .sin_t =   7, .cos_t = 256 },
  [42] = { .timer =  2, .sin_t =   8, .cos_t = 256 },
  [43] = { .timer =  3, .sin_t =   9, .cos_t = 256 },
  [44] = { .timer =  3, .sin_t =  10, .cos_t = 256 },
  [45] = { .timer =  3, .sin_t =  11, .cos_t = 256 },
  [46] = { .timer =  3, .sin_t =  12, .cos_t = 256 },
  [47] = { .timer =  4, .sin_t =  13, .cos_t = 256 },
  [48] = { .timer =  4, .sin_t =  14, .cos_t = 256 },
  [49] = { .timer =  4, .sin_t =  15, .cos_t = 256 },
  [50] = { .timer =  5, .sin_t =  16, .cos_t = 256 },
  [51] = { .timer =  5, .sin_t =  17, .cos_t = 255 },
  [52] = { .timer =  6, .sin_t =  18, .cos_t = 255 },
  [53] = { .timer =  6, .sin_t =  19, .cos_t = 255 },
  [54] = { .timer =  7, .sin_t =  20, .cos_t = 255 },
  [55] = { .timer =  7, .sin_t =  21, .cos_t = 255 },
  [56] = { .timer =  8, .sin_t =  22, .cos_t = 255 },
  [57] = { .timer =  9, .sin_t =  23, .cos_t = 255 },
  [58] = { .timer = 10, .sin_t =  24, .cos_t = 255 },
  [59] = { .timer = 11, .sin_t =  25, .cos_t = 255 },
  [60] = { .timer = 12, .sin_t =  26, .cos_t = 255 },
  [61] = { .timer = 14, .sin_t =  27, .cos_t = 255 },
  [62] = { .timer = 16, .sin_t =  28, .cos_t = 254 },
  [63] = { .timer = 18, .sin_t =  29, .cos_t = 254 },
  [64] = { .timer = 20, .sin_t =  30, .cos_t = 254 },
  [65] = { .timer = 22, .sin_t =  31, .cos_t = 254 },
  [66] = { .timer = 24, .sin_t =  32, .cos_t = 254 },
  [67] = { .timer = 26, .sin_t =  33, .cos_t = 254 },
  [68] = { .timer = 60, .sin_t =  34, .cos_t = 254 },
};
