#pragma once

#define kXrayHdmaWindow2Object (*(SpawnHdmaObject_Args*)RomFixedPtr(0x91caf2))
#define kXrayBlockData ((XrayBlockData*)RomFixedPtr(0x91d2d6))
#define kXrayBlockData ((XrayBlockData*)RomFixedPtr(0x91d2d6))
#define kSamusPalette_Normal ((uint16*)RomFixedPtr(0x91d727))
#define kSamusPalette_HyperBeam ((uint16*)RomFixedPtr(0x91d829))
#define kSamusPalette_NonPseudoScrew ((uint16*)RomFixedPtr(0x91d7d5))
#define kSamusPalette_PseudoScrew ((uint16*)RomFixedPtr(0x91d7ff))
#define kSamus_VisorColors ((uint16*)RomFixedPtr(0x9ba3c0))
#define kSamus_SpeedBoostingPalettes ((uint16*)RomFixedPtr(0x91d998))
#define kSamus_HyperBeamPalettes ((uint16*)RomFixedPtr(0x91d99e))
#define kSamusPal_ScrewAttack ((uint16*)RomFixedPtr(0x91da4a))
#define kSamusPal_SpeedBoost ((uint16*)RomFixedPtr(0x91daa9))
#define kSamusPal_SpeedBoostShine ((uint16*)RomFixedPtr(0x91db10))
#define kSamusPal_Shinespark ((uint16*)RomFixedPtr(0x91db75))
#define kSamusPal_CrystalFlash0to9 ((SamusCrystalFlashPalTable*)RomFixedPtr(0x91dc00))
#define kSamusPal_CrystalFlash10to15 ((uint16*)RomFixedPtr(0x91dc28))
#define kSamusPose_Falling ((uint16*)RomFixedPtr(0x91e921))
#define kSamusPose_Landing ((uint16*)RomFixedPtr(0x91e9f3))
#define kSamusPose_RanIntoWall ((uint16*)RomFixedPtr(0x91eb74))
#define kSamusTurnPose_Standing ((uint8*)RomFixedPtr(0x91f9c2))
#define kSamusTurnPose_Crouching ((uint8*)RomFixedPtr(0x91f9cc))
#define kSamusTurnPose_Jumping ((uint8*)RomFixedPtr(0x91f9d6))
#define kSamusTurnPose_Falling ((uint8*)RomFixedPtr(0x91f9e0))
#define kSamusTurnPose_Moonwalk ((uint8*)RomFixedPtr(0x91f9ea))
