#pragma once

#define kEnemyInit_MorphBallEye_InstrListPtrs ((uint16*)RomFixedPtr(0xa890da))
#define kYappingMaw_Constant0 (*(uint16*)RomFixedPtr(0xa8a0a7))
#define kYappingMaw_Constant1 (*(uint16*)RomFixedPtr(0xa8a0a9))
#define kYappingMaw_Constant2 (*(uint16*)RomFixedPtr(0xa8a0ab))
#define kYappingMaw_Constant3 (*(uint16*)RomFixedPtr(0xa8a0ad))
#define kYappingMaw_Constant4 (*(uint16*)RomFixedPtr(0xa8a0b3))
#define kYappingMaw_Constant5 (*(uint16*)RomFixedPtr(0xa8a0b5))
#define kYappingMaw_Constant6 (*(uint16*)RomFixedPtr(0xa8a0b7))
#define kYappingMaw_Constant7 (*(uint16*)RomFixedPtr(0xa8a0b9))
#define kYappingMaw_Constant8 (*(uint16*)RomFixedPtr(0xa8a0bb))
#define kYappingMaw_Constant9 (*(uint16*)RomFixedPtr(0xa8a0bd))
#define kYappingMaw_Constant10 (*(uint16*)RomFixedPtr(0xa8a0c3))
#define kYappingMaw_Constant11 (*(uint16*)RomFixedPtr(0xa8a0c5))
#define kYappingMaw_InstrListPtrs ((uint16*)RomFixedPtr(0xa8a097))
#define kNorfairLavaMan_Palette ((uint16*)RomFixedPtr(0xa8ac1c))
#define kNorfairLavaMan_Tab2 ((uint16*)RomFixedPtr(0xa8af79))
#define kNorfairLavaMan_Tab0 ((uint16*)RomFixedPtr(0xa8af55))
#define kNorfairLavaMan_Tab1 ((uint16*)RomFixedPtr(0xa8af67))
#define kBeetom_SamusNotInProximityFuncPtrs ((uint16*)RomFixedPtr(0xa8b74e))
#define kMaridiaFloater_InstrListPtrs ((uint16*)RomFixedPtr(0xa8c599))
#define kEnemyInit_WreckedShipRobotDeactivated_InstrListPtrs ((uint16*)RomFixedPtr(0xa8cc30))
#define kEnemyInit_WreckedShipOrbs_InstrListPtrs ((uint16*)RomFixedPtr(0xa8e380))
#define kEnemyInit_WreckedShipSpark_InstrListPtrs ((uint16*)RomFixedPtr(0xa8e682))
#define kEnemyInit_WreckedShipSpark_FuncPtrs ((uint16*)RomFixedPtr(0xa8e688))
#define kBlueBrinstarFaceBlock_GlowPalette ((uint16*)RomFixedPtr(0xa8e7cc))
#define kKiHunter_InstrListPtrs ((uint16*)RomFixedPtr(0xa8f3b0))
