#pragma once

#define kEnemyInit_Torizo_InstrListPtrs ((uint16*)RomFixedPtr(0xaac967))
#define kEnemyInit_TourianEntranceStatue_InstrListPtrs ((uint16*)RomFixedPtr(0xaad810))
#define kEnemyInit_TourianEntranceStatue_PaletteTab0 ((uint16*)RomFixedPtr(0xaad765))
#define kEnemyInit_TourianEntranceStatue_PaletteTab1 ((uint16*)RomFixedPtr(0xaad785))
#define kShaktool_InstrListPtrs0 ((uint16*)RomFixedPtr(0xaadf13))
#define kShaktool_InstrListPtrs1 ((uint16*)RomFixedPtr(0xaadf21))
#define kSine ((uint16*)RomFixedPtr(0xaae0bd))
#define kCosine ((uint16*)RomFixedPtr(0xaae13d))
#define kNegativeSine ((uint16*)RomFixedPtr(0xaae1bd))
#define kNegativeCosine_0 ((uint16*)RomFixedPtr(0xaae23d))
#define kNegativeCosine ((uint16*)RomFixedPtr(0xaae03d))
#define kShaktool_InstrListPtrs2 ((uint16*)RomFixedPtr(0xaadd15))
#define kEnemyInit_Shaktool_PropertiesIndices ((uint16*)RomFixedPtr(0xaade95))
#define kEnemyInit_Shaktool_RamOffsetIndices ((uint16*)RomFixedPtr(0xaadea3))
#define kEnemyInit_Shaktool_InitialAnglesIndices ((uint16*)RomFixedPtr(0xaadeb1))
#define kEnemyInit_Shaktool_FuncPtrs ((uint16*)RomFixedPtr(0xaadedb))
#define kEnemyInit_Shaktool_ZeroIndices ((uint16*)RomFixedPtr(0xaadef7))
#define kEnemyInit_Shaktool_LayerControlIndices ((uint16*)RomFixedPtr(0xaadecd))
#define kShaktool_XDirectionIndices ((uint16*)RomFixedPtr(0xaae630))
#define kShaktool_SamusXPositionIndices ((uint16*)RomFixedPtr(0xaae670))
#define kShaktool_SamusYPositionIndices ((uint16*)RomFixedPtr(0xaae6b0))
#define kN00bTubeCracks_Palette2 ((uint16*)RomFixedPtr(0xaae2dd))
#define kEnemyInit_ChozoStatue_InstrListPtrs ((uint16*)RomFixedPtr(0xaae7a2))
